# Generated by Django 5.0 on 2023-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=100)),
                ('orgOwner', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['orgName'],
            },
        ),
    ]
