# Generated by Django 5.0 on 2023-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=100)),
                ('roomName', models.CharField(max_length=100)),
                ('roomCapacity', models.IntegerField(default=0)),
                ('roomWorkingHours', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['roomName'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='orgServerId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
