# Generated by Django 5.0 on 2023-12-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0002_room_organization_orgserverid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(max_length=100)),
                ('eventTitle', models.CharField(max_length=100)),
                ('eventDescription', models.CharField(max_length=100)),
                ('eventCategory', models.CharField(max_length=100)),
                ('eventCapacity', models.IntegerField(default=0)),
                ('eventDuration', models.IntegerField(default=0)),
                ('eventWeekly', models.IntegerField(default=0)),
                ('eventPermissions', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['eventTitle'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='roomPermissions',
            field=models.CharField(default='', max_length=100),
        ),
    ]
