# Generated by Django 5.0 on 2024-01-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0003_event_room_roompermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventHours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
